services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      # - <our-computer>:<container>
      - ./images:/app/images
    depends_on:
      - db
    # Testing (remove before deploying)
    # ports:
    #   - 3000:3000
    
  caddy:
    image: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile